import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
   title: 'Blog Next App',
   description: 'Generated by create next app',
};

async function getData() {
   const response = await fetch('https://jsonplaceholder.typicode.com/posts', {
      next: {
         revalidate: 60,
      },
   });
   return response.json();
}

const Blog = async () => {
   const posts = await getData();
   return (
      <>
         <h1>Blog</h1>
         <ul className="flex flex-col items-center gap3">
            {posts.map((item: any) => (
               <li key={item.id}>
                  <Link href={`/blog/${item.id}`}>{item.title}</Link>
               </li>
            ))}
         </ul>
      </>
   );
};

export default Blog;
